### ISSUE TITLE
Split version into three number fields

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#22]
Splitting version numbers into three number fields could make it easier to automate comparison and management of different versions of applications built on Karbon.

Quick example below:

KarbonVersion_Major: 0
KarbonVersion_Minor: 9
KarbonVersion_Patch: 4

KarbonVersion = 
`KarbonVersion_Major & "." & KarbonVersion_Minor & "." & KarbonVersion_Patch`

This would allow simple numeric comparisons between each version segment and remove the need to deal with text comparison issues. For example where version 9 appears to be newer than version 10.

**Comment by toddgeist** [comment]
interesting idea. We intend to be Semver compliant, and this could make it easier. But it isn't yet clear how useful it will be.

**Comment by davegraham92120** [comment]
@alecgregory: For the vast majority of folks adopting Karbon, they will download it and immediately begin to customize it, which essentially permanently forks it since there's no way to merge changes in a FileMaker system. For this reason, we only thought that Karbon versions were relevant to this project, so we can keep track of the features added and bugs fixed based on a release. Let us know if you see a use case for this to be more widely used. 

You can compare version strings now with the following calc. I'd prefer this approach over setting three separate fields during the build process.

```
Let ( [ 
	~version = "1.31.4" ; 
	~versionList = Substitute ( ~version ; "." ; ¶ ) ; 
	~versionOut =  
		Right ( "00" & GetValue ( ~versionList ; 1 ) ; 3 ) &
		Right ( "00" & GetValue ( ~versionList ; 2 ) ; 3 ) &
		Right ( "00" & GetValue ( ~versionList ; 3 ) ; 3 ) 

] ; 
	GetAsNumber ( ~versionOut )
) = 1031004
```

The result is a number that can be used to compare versions.
